apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: duplicati
  name: duplicati
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: duplicati
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/labapp-default: "true"
        io.kompose.service: duplicati
    spec:
      containers:
        - image: linuxserver/duplicati
          name: duplicati
          ports:
            - containerPort: 8200
              hostPort: 8200
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: duplicati-claim0
            - mountPath: /data
              name: duplicati-claim1
      restartPolicy: Always
      volumes:
        - name: duplicati-claim0
          persistentVolumeClaim:
            claimName: duplicati-claim0
        - name: duplicati-claim1
          persistentVolumeClaim:
            claimName: duplicati-claim1
