apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: jackett
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jackett
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/labapp-default: "true"
        io.kompose.service: jackett
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Berlin
          image: linuxserver/jackett
          name: jackett
          ports:
            - containerPort: 9117
              hostPort: 9117
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: jackett-claim0
      restartPolicy: Always
      volumes:
        - name: jackett-claim0
          persistentVolumeClaim:
            claimName: jackett-claim0
