apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/labapp-default: "true"
        io.kompose.service: nextcloud
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: db
          image: nextcloud
          name: nextcloud
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-claim0
      restartPolicy: Always
      volumes:
        - name: nextcloud-claim0
          persistentVolumeClaim:
            claimName: nextcloud-claim0
