apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: photoprism
  name: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: photoprism
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/labapp-default: "true"
        io.kompose.service: photoprism
    spec:
      containers:
        - env:
            - name: PHOTOPRISM_ADMIN_PASSWORD
              value: '"admin"'
            - name: PHOTOPRISM_HTTP_PORT
              value: "2342"
            - name: PHOTOPRISM_ORIGINALS_LIMIT
              value: "1000"
            - name: PHOTOPRISM_PUBLIC
              value: '"true"'
            - name: PHOTOPRISM_READONLY
              value: '"false"'
          image: photoprism/photoprism:latest
          name: photoprism
          ports:
            - containerPort: 2342
              hostPort: 2342
              protocol: TCP
          volumeMounts:
            - mountPath: /photoprism/originals
              name: photoprism-claim0
            - mountPath: /photoprism/storage
              name: photoprism-claim1
            - mountPath: /photoprism/import
              name: photoprism-claim2
            - mountPath: /photoprism/database
              name: photoprism-claim3
      restartPolicy: Always
      volumes:
        - name: photoprism-claim0
          persistentVolumeClaim:
            claimName: photoprism-claim0
        - name: photoprism-claim1
          persistentVolumeClaim:
            claimName: photoprism-claim1
        - name: photoprism-claim2
          persistentVolumeClaim:
            claimName: photoprism-claim2
        - name: photoprism-claim3
          persistentVolumeClaim:
            claimName: photoprism-claim3
