apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: photoprism-claim3
  name: photoprism-claim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
